# Generated by Django 2.2 on 2023-10-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('person', models.CharField(max_length=2)),
                ('place', models.TextField()),
                ('price', models.IntegerField()),
                ('date', models.TextField()),
            ],
        ),
    ]
